anguage: go

go:
  - "1.13"

install:
  - make build

script:
  - make deps
  - make test-coverage
  - make lint
  - make build

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: always
