title: "Goa"
theme: just-the-docs
search_enabled: true
search_tokenizer_separator: /[\s/]+/
aux_links:
  "Goa on GitHub":
    - "//github.com/wesovilabs/goa"
heading_anchors: true
footer_content: "Copyright &copy; 2019 Iván Corrales Solera. Distributed by an <a href=\"https://github.com/wesovilabs/goa/tree/master/LICENSE.md\">MIT license.</a>"
email: ivan.corrales.solera@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: wesovilabs
github_username:  wesovilabs

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
