title: Goa
remote_theme: pmarsceill/just-the-docs
search_enabled: true
search_tokenizer_separator: /[\s/]+/
aux_links:
  "Goa on GitHub":
    - "//github.com/wesovilabs/goa"
heading_anchors: true
footer_content: "Copyright &copy; 2019 Iván Corrales Solera. Distributed by an <a href=\"https://github.com/wesovilabs/goa/tree/master/LICENSE.md\">MIT license.</a>"
email: ivan.corrales.solera@gmail.com

permalink: pretty

ga_tracking: UA-153120957-1

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme

github_username: wesovilabs
